// Public S3 footage; videos load only when a portfolio card is opened.
export const videos = [
  {
    id: "event-after",
    title: "Арга хэмжээний мөчүүд",
    originalFile: "2 after.mp4",
    category: "EVENT HIGHLIGHTS",
    poster: "/images/events/event-after.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/2+after.mp4",
    isDemo: false,
  },
  {
    id: "event-film",
    title: "Баярын уур амьсгал",
    originalFile: "2.mp4",
    category: "EVENT FILM",
    poster: "/images/events/event-film.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/2.mp4",
    isDemo: false,
  },
  {
    id: "ballet-after",
    title: "Балет · Тоглолтын мөчүүд",
    originalFile: "BALLET AFTER OK.mp4",
    category: "PERFORMANCE",
    poster: "/images/events/ballet-after.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/BALLET+AFTER+OK.mp4",
    isDemo: false,
  },
  {
    id: "ballet-short",
    title: "Балет · Богино түүх",
    originalFile: "Ballet bogino stork.mp4",
    category: "PERFORMANCE",
    poster: "/images/events/ballet-short.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/Ballet+bogino+stork.mp4",
    isDemo: false,
  },
  {
    id: "bsg",
    title: "BSG · Арга хэмжээ",
    originalFile: "BSG- 09-05 ok.mp4",
    category: "EVENT HIGHLIGHTS",
    poster: "/images/events/bsg.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/BSG-+09-05+ok.mp4",
    isDemo: false,
  },
  {
    id: "leaders",
    title: "Leaders · New Year 2025",
    originalFile: "Leaders NY 2025 (1).mp4",
    category: "CORPORATE EVENT",
    poster: "/images/events/leaders.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/Leaders+NY+2025+(1).mp4",
    isDemo: false,
  },
  {
    id: "leaders-mongolia",
    title: "Leaders of Mongolia · Шинэ жилийн баяр",
    originalFile: "Leaders of Mongolia NY ok.mp4",
    category: "CORPORATE EVENT",
    poster: "/images/events/leaders-mongolia.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/Leaders+of+Mongolia+NY+ok.mp4",
    isDemo: false,
  },
  {
    id: "serchmaa",
    title: "Сэрчмаа · Тоглолтын мөчүүд",
    originalFile: "Serchmaa 04-10.mp4",
    category: "PERFORMANCE",
    poster: "/images/events/serchmaa.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/Serchmaa+04-10.mp4",
    isDemo: false,
  },
  {
    id: "sm-event",
    title: "SM · Арга хэмжээ",
    originalFile: "SM 01-31 mon.mp4",
    category: "EVENT FILM",
    poster: "/images/events/sm-event.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/SM+01-31+mon.mp4",
    isDemo: false,
  },
  {
    id: "sod-mongol-after",
    title: "Сод Монгол · Онцлох агшнууд",
    originalFile: "Sod Mongol AFTER.mp4",
    category: "CORPORATE EVENT",
    poster: "/images/events/sod-mongol-after.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/Sod+Mongol+AFTER.mp4",
    isDemo: false,
  },
  {
    id: "sod-mongol-film",
    title: "Сод Монгол · Арга хэмжээний бичлэг",
    originalFile: "Sod tursun Mongol ok.mp4",
    category: "EVENT FILM",
    poster: "/images/events/sod-mongol-film.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/Sod+tursun+Mongol+ok.mp4",
    isDemo: false,
  },
  {
    id: "terguun-chansaa",
    title: "Тэргүүн чансаа · Онцлох агшнууд",
    originalFile: "Terguun chansaa- AFTER (1).mp4",
    category: "EVENT HIGHLIGHTS",
    poster: "/images/events/terguun-chansaa.jpg",
    src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/Terguun+chansaa-+AFTER+(1).mp4",
    isDemo: false,
  },
];

export const heroVideo = {
  src: "https://angel-ina-ika.s3.us-east-1.amazonaws.com/Leaders+NY+2025+(1).mp4",
  poster: "/images/events/leaders-hero.jpg",
  endSeconds: 13,
};
